// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNn9K2C7uI_KptQ9dttyR64W66GfCnoFo',
    appId: '1:562483351517:web:bb93d31d58f480a9e87034',
    messagingSenderId: '562483351517',
    projectId: 'employee-389e1',
    authDomain: 'employee-389e1.firebaseapp.com',
    databaseURL: 'https://employee-389e1-default-rtdb.firebaseio.com',
    storageBucket: 'employee-389e1.appspot.com',
    measurementId: 'G-05ZRPXF98E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOR2MiY8YkoHr5_2xOLm7MuoRq0_uYmrQ',
    appId: '1:562483351517:android:626473977f57262ae87034',
    messagingSenderId: '562483351517',
    projectId: 'employee-389e1',
    databaseURL: 'https://employee-389e1-default-rtdb.firebaseio.com',
    storageBucket: 'employee-389e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-Esjhf2jj1tJpnKvPni89NhlGq67sY5s',
    appId: '1:562483351517:ios:96d335bfcfe18b16e87034',
    messagingSenderId: '562483351517',
    projectId: 'employee-389e1',
    databaseURL: 'https://employee-389e1-default-rtdb.firebaseio.com',
    storageBucket: 'employee-389e1.appspot.com',
    iosBundleId: 'com.example.employee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-Esjhf2jj1tJpnKvPni89NhlGq67sY5s',
    appId: '1:562483351517:ios:5fdd75096d44b2c6e87034',
    messagingSenderId: '562483351517',
    projectId: 'employee-389e1',
    databaseURL: 'https://employee-389e1-default-rtdb.firebaseio.com',
    storageBucket: 'employee-389e1.appspot.com',
    iosBundleId: 'com.example.employee.RunnerTests',
  );
}
